// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NAIware.Rules.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RulesEngineFeature : object, global::Xunit.IClassFixture<RulesEngineFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Rules Engine", "    As a developer\r\n    I want to use the rules engine to evaluate boolean expres" +
                "sions\r\n    So that I can implement business rule logic", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RulesEngine.feature"
#line hidden
        
        public RulesEngineFeature(RulesEngineFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/RulesEngine.feature", "Feature: Rules Engine\r\n    As a developer\r\n    I want to use the rules engine to " +
                    "evaluate boolean expressions\r\n    So that I can implement business rule logic\r\n\r" +
                    "\nScenario: Simple equality rule evaluates to true\r\n    Given a rules engine with" +
                    " an integer parameter \"Age\" set to 25\r\n    When I add a rule \"Age = 25\"\r\n    And" +
                    " I execute the rules engine\r\n    Then the executed rule count should be 1\r\n\r\nSce" +
                    "nario: Simple equality rule evaluates to false\r\n    Given a rules engine with an" +
                    " integer parameter \"Age\" set to 30\r\n    When I add a rule \"Age = 25\"\r\n    And I " +
                    "execute the rules engine\r\n    Then the executed rule count should be 0\r\n\r\nScenar" +
                    "io: Greater than comparison\r\n    Given a rules engine with an integer parameter " +
                    "\"Score\" set to 85\r\n    When I add a rule \"Score > 70\"\r\n    And I execute the rul" +
                    "es engine\r\n    Then the executed rule count should be 1\r\n\r\nScenario: Less than o" +
                    "r equal comparison\r\n    Given a rules engine with an integer parameter \"Price\" s" +
                    "et to 100\r\n    When I add a rule \"Price <= 100\"\r\n    And I execute the rules eng" +
                    "ine\r\n    Then the executed rule count should be 1\r\n\r\nScenario: Not equal compari" +
                    "son\r\n    Given a rules engine with an integer parameter \"Status\" set to 1\r\n    W" +
                    "hen I add a rule \"Status != 0\"\r\n    And I execute the rules engine\r\n    Then the" +
                    " executed rule count should be 1\r\n\r\nScenario: Complex rule with AND\r\n    Given a" +
                    " rules engine with integer parameters \"Age\" set to 25 and \"Score\" set to 90\r\n   " +
                    " When I add a rule \"Age >= 18 and Score > 80\"\r\n    And I execute the rules engin" +
                    "e\r\n    Then the executed rule count should be 1\r\n\r\nScenario: Complex rule with A" +
                    "ND fails when one condition is false\r\n    Given a rules engine with integer para" +
                    "meters \"Age\" set to 15 and \"Score\" set to 90\r\n    When I add a rule \"Age >= 18 a" +
                    "nd Score > 80\"\r\n    And I execute the rules engine\r\n    Then the executed rule c" +
                    "ount should be 0\r\n\r\nScenario: Parse and render a rule expression\r\n    Given a ru" +
                    "les engine with an integer parameter \"X\" set to 10\r\n    When I parse the rule \"X" +
                    " > 5\"\r\n    Then the rendered expression should contain \"X\"\r\n    And the rendered" +
                    " expression should contain \">\"\r\n    And the rendered expression should contain \"" +
                    "5\"\r\n\r\nScenario: Multiple rules with only some passing\r\n    Given a rules engine " +
                    "with an integer parameter \"Value\" set to 50\r\n    When I add a rule \"Value > 100\"" +
                    "\r\n    And I add a rule \"Value = 50\"\r\n    And I add a rule \"Value < 10\"\r\n    And " +
                    "I execute the rules engine\r\n    Then the executed rule count should be 1\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/RulesEngine.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Rules Engine", "    As a developer\r\n    I want to use the rules engine to evaluate boolean expres" +
                        "sions\r\n    So that I can implement business rule logic", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Simple equality rule evaluates to true", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"Age\" set to 25", null, null, "39187fe81e6f57528093039d848aa662"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Age = 25\"", null, null, "f1c37662731548558bf8e8ac672643cc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "d590b2c2c0710f56961ac9c73f08a3db"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 1", null, null, "76b806469e35ca5590bcf8fdea21de49")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a24f72022f927251b532c1041e073574")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Simple equality rule evaluates to false", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"Age\" set to 30", null, null, "8f3ac2e29a73c1509debc9fd24b626ec"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Age = 25\"", null, null, "fa43b8999b1f3951b7dd869042644856"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "15622ed6c41fef5884eea75eb4738029"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 0", null, null, "13ad38615b45cd52ac702f56621e956f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "42de0c24f0643a53a81096ac076c50bc")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Greater than comparison", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"Score\" set to 85", null, null, "a0e9fb721fa55b51ab5d0e6b0860d09a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Score > 70\"", null, null, "8cb8786c63767f51b183cb2543eae072"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "a07c7d1169f16150b25ea0cc52af2529"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 1", null, null, "9515987ba81c9a5b925f97caa603691b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b814d6aef8cab25f95cb57fdfb7a0e76")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Less than or equal comparison", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"Price\" set to 100", null, null, "f131185925f0b05f93e5db7f235a908b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Price <= 100\"", null, null, "53d4372e173ece548827780c9cbf2733"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "d12d6fee89fc6755ad34d02e3d0c0486"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 1", null, null, "9d2b60cd4bda2d57b88c85eb7b5020e8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ed39b1106c19f851acf9550d8f368f19")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Not equal comparison", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"Status\" set to 1", null, null, "74361e6e07a7525e89ca6e3c83c40a9a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Status != 0\"", null, null, "2231d7b64b62c7519dd30e5ca92ad09a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "075bd26b5e90dc5f825c6dea8b1414a9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 1", null, null, "e64714299071f155ace1dad56eee2c23")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e51563fe5b99f95fadb32240b37714b3")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Complex rule with AND", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with integer parameters \"Age\" set to 25 and \"Score\" set to 90", null, null, "55e9b9eb9da08f53b3e6c3fe99261f02"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Age >= 18 and Score > 80\"", null, null, "3d869946d51062569121acc10f33c86f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "d9d1d2697efe8a50bb9d9688284a6660"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 1", null, null, "6e5fd78833989b57993d47851d44bee1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "47ca89e2b551be5c96f67e048fc68e19")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Complex rule with AND fails when one condition is false", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with integer parameters \"Age\" set to 15 and \"Score\" set to 90", null, null, "fcdcfffbb982fa52aa935728065c59ca"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Age >= 18 and Score > 80\"", null, null, "aad19d53800fe456bc73c99c09130e92"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "776eb0465720055b9d3def329361e57d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 0", null, null, "f629f240779a495a9a6b37e84becfe31")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "671b3e27de5a615989915704b15c26ef")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Parse and render a rule expression", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"X\" set to 10", null, null, "a16299f98a70ce5d821c7c8e6302660d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I parse the rule \"X > 5\"", null, null, "5829b7269023615dbcf5f62f56b9db05"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the rendered expression should contain \"X\"", null, null, "b2f99f97b90913559ce5f87a3a73fdd6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the rendered expression should contain \">\"", null, null, "c9177be1dc867d5bab71840c42577e98"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the rendered expression should contain \"5\"", null, null, "70b670664385bc5e85be097a0dcb1f1b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e7abc96450fcb555a5baa80cb4b626e5")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Multiple rules with only some passing", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a rules engine with an integer parameter \"Value\" set to 50", null, null, "55d25c9ca34d7454ba19659ff2b7eb98"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I add a rule \"Value > 100\"", null, null, "a5cabd557e2a1b58a844bdac5bb0e860"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I add a rule \"Value = 50\"", null, null, "fa4a0c3e2e4d6350a9eca3dc1f7e5715"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I add a rule \"Value < 10\"", null, null, "9334dc769798395c82cf7b9d82fd9fbe"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I execute the rules engine", null, null, "fc5098187b4d725ebcce5a001b95bbce"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the executed rule count should be 1", null, null, "ee592a12ef1d6754aa04e2e1ad126cb2")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "97421684584252558161d50395ea8ef7"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("76593ad0eee7445f934e1ba86eeaae82", "Features/RulesEngine.feature", "Simple equality rule evaluates to true", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "39187fe81e6f57528093039d848aa662"}), "28dd28da03a306569799a939f0cf1fb7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"Age\" set to 25"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f1c37662731548558bf8e8ac672643cc"}), "c13cd9e1b4a1b25ba744238f57df5a9d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Age = 25\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d590b2c2c0710f56961ac9c73f08a3db"}), "07897c54768d9757a407e6bf7da7ab93", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "76b806469e35ca5590bcf8fdea21de49"}), "c3e921fa0076aa5d919bc27f62c4ca27", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "a24f72022f927251b532c1041e073574"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("268f96fb7da6355a843bf8b63a82b077", "Features/RulesEngine.feature", "Simple equality rule evaluates to false", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8f3ac2e29a73c1509debc9fd24b626ec"}), "c40f1bb1a0965353b03102fe2f4421f6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"Age\" set to 30"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fa43b8999b1f3951b7dd869042644856"}), "62938bf0a4865f57b525c808405711dc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Age = 25\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "15622ed6c41fef5884eea75eb4738029"}), "494a24c5e1a7cc5a9f5373b8e4ffe6ef", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "13ad38615b45cd52ac702f56621e956f"}), "4c2859b1b986bb57b119011d321b4277", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 0")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "42de0c24f0643a53a81096ac076c50bc"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a1c35306a2a3055880f151aba78f8d10", "Features/RulesEngine.feature", "Greater than comparison", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a0e9fb721fa55b51ab5d0e6b0860d09a"}), "5c30a83977ce19569572b253fe79d318", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"Score\" set to 85"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8cb8786c63767f51b183cb2543eae072"}), "9aff5a3a9a588254b0196d92c09b66e4", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Score > 70\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a07c7d1169f16150b25ea0cc52af2529"}), "161dbff01d4ee65593db2e689cb26957", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9515987ba81c9a5b925f97caa603691b"}), "ef6e16ebb413065cac8bdde23c94e77c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "b814d6aef8cab25f95cb57fdfb7a0e76"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("83ee4d237aa07f5285a129ecc015a30d", "Features/RulesEngine.feature", "Less than or equal comparison", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f131185925f0b05f93e5db7f235a908b"}), "18348647edd69450ab26b5bd952f1429", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"Price\" set to 100"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "53d4372e173ece548827780c9cbf2733"}), "99b9933a065aa55e8fbde2cc4ecdde3a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Price <= 100\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d12d6fee89fc6755ad34d02e3d0c0486"}), "0e1644114d00fe57bc0e3a074964291a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9d2b60cd4bda2d57b88c85eb7b5020e8"}), "2857c4fb2dbd3450a1e9774cc7f46aca", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "ed39b1106c19f851acf9550d8f368f19"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a710795811a1a15b8cc2f7ea2894febc", "Features/RulesEngine.feature", "Not equal comparison", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "74361e6e07a7525e89ca6e3c83c40a9a"}), "07e20264e2b7ac55897be6db68929873", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"Status\" set to 1"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2231d7b64b62c7519dd30e5ca92ad09a"}), "c73626e812d3e1579f48f7c171588e9f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Status != 0\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "075bd26b5e90dc5f825c6dea8b1414a9"}), "d163e798fc0600589b33710df079484b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e64714299071f155ace1dad56eee2c23"}), "afaa1484e50bd55c91bd2004693e20d5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e51563fe5b99f95fadb32240b37714b3"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("2364abd500f03c50a9a870185c16088c", "Features/RulesEngine.feature", "Complex rule with AND", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55e9b9eb9da08f53b3e6c3fe99261f02"}), "93e3822e57dbb9549d1ab35cddae0f69", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with integer parameters \"Age\" set to 25 and \"Score\" set to 90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3d869946d51062569121acc10f33c86f"}), "dbe93ed02f154053a6d04d658f85e024", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Age >= 18 and Score > 80\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d9d1d2697efe8a50bb9d9688284a6660"}), "c5a72efc650e3652a50d5419a58e6c50", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6e5fd78833989b57993d47851d44bee1"}), "9f524e633191c6518695d0c51d33e671", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "47ca89e2b551be5c96f67e048fc68e19"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f642d985a8d74b56a4ac75387ec2fb53", "Features/RulesEngine.feature", "Complex rule with AND fails when one condition is false", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fcdcfffbb982fa52aa935728065c59ca"}), "a7dbf1839477715ba460a3400a05bcb8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with integer parameters \"Age\" set to 15 and \"Score\" set to 90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "aad19d53800fe456bc73c99c09130e92"}), "8e1eeaee4bf2bb56b09f88a25192be4d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Age >= 18 and Score > 80\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "776eb0465720055b9d3def329361e57d"}), "a8e60aec6ac69d5cb1a0734c8cdc39bf", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f629f240779a495a9a6b37e84becfe31"}), "62de3700c3f26752b25e53c02602c6e4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 0")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "671b3e27de5a615989915704b15c26ef"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("c13e5966d9f6655d86a581accb553c36", "Features/RulesEngine.feature", "Parse and render a rule expression", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a16299f98a70ce5d821c7c8e6302660d"}), "f43a8006e45be25fb5b86f32d9674577", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"X\" set to 10"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5829b7269023615dbcf5f62f56b9db05"}), "f56a5fbaf74b545ea07d14d1b9b523ab", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I parse the rule \"X > 5\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b2f99f97b90913559ce5f87a3a73fdd6"}), "186aa05681533d5b941a53d4ae7f3779", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the rendered expression should contain \"X\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c9177be1dc867d5bab71840c42577e98"}), "8b894c7e8d7a8251ae6d45500eee1db2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the rendered expression should contain \">\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70b670664385bc5e85be097a0dcb1f1b"}), "2089ee31e3da1758abed0ee3a5f11167", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the rendered expression should contain \"5\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e7abc96450fcb555a5baa80cb4b626e5"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6a3515ea8b9e91568baf8ca6efd1a2b8", "Features/RulesEngine.feature", "Multiple rules with only some passing", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55d25c9ca34d7454ba19659ff2b7eb98"}), "1f4ec80104bc3656a9bfe4e04fd6190f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a rules engine with an integer parameter \"Value\" set to 50"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a5cabd557e2a1b58a844bdac5bb0e860"}), "48669fdc2e26965dac87a6a694ddceb4", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Value > 100\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fa4a0c3e2e4d6350a9eca3dc1f7e5715"}), "0fc48c728e74b55e85ce87fac67e08ea", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Value = 50\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9334dc769798395c82cf7b9d82fd9fbe"}), "3c65f3cc16f4515ea4e31ace7f4ab95f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I add a rule \"Value < 10\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fc5098187b4d725ebcce5a001b95bbce"}), "10b5447f8192e15f84015bc8ef2d9232", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I execute the rules engine"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ee592a12ef1d6754aa04e2e1ad126cb2"}), "be92f2054df252539a254dede19aa911", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the executed rule count should be 1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "97421684584252558161d50395ea8ef7"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(RulesEngineFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(RulesEngineFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(RulesEngineFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Simple equality rule evaluates to true")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Simple equality rule evaluates to true")]
        public async global::System.Threading.Tasks.Task SimpleEqualityRuleEvaluatesToTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Simple equality rule evaluates to true", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("a rules engine with an integer parameter \"Age\" set to 25", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("I add a rule \"Age = 25\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.ThenAsync("the executed rule count should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Simple equality rule evaluates to false")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Simple equality rule evaluates to false")]
        public async global::System.Threading.Tasks.Task SimpleEqualityRuleEvaluatesToFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Simple equality rule evaluates to false", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("a rules engine with an integer parameter \"Age\" set to 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("I add a rule \"Age = 25\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.ThenAsync("the executed rule count should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Greater than comparison")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Greater than comparison")]
        public async global::System.Threading.Tasks.Task GreaterThanComparison()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Greater than comparison", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("a rules engine with an integer parameter \"Score\" set to 85", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("I add a rule \"Score > 70\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync("the executed rule count should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Less than or equal comparison")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Less than or equal comparison")]
        public async global::System.Threading.Tasks.Task LessThanOrEqualComparison()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Less than or equal comparison", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("a rules engine with an integer parameter \"Price\" set to 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync("I add a rule \"Price <= 100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.ThenAsync("the executed rule count should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Not equal comparison")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Not equal comparison")]
        public async global::System.Threading.Tasks.Task NotEqualComparison()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Not equal comparison", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("a rules engine with an integer parameter \"Status\" set to 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.WhenAsync("I add a rule \"Status != 0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.ThenAsync("the executed rule count should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Complex rule with AND")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Complex rule with AND")]
        public async global::System.Threading.Tasks.Task ComplexRuleWithAND()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complex rule with AND", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("a rules engine with integer parameters \"Age\" set to 25 and \"Score\" set to 90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("I add a rule \"Age >= 18 and Score > 80\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.ThenAsync("the executed rule count should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Complex rule with AND fails when one condition is false")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Complex rule with AND fails when one condition is false")]
        public async global::System.Threading.Tasks.Task ComplexRuleWithANDFailsWhenOneConditionIsFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complex rule with AND fails when one condition is false", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
    await testRunner.GivenAsync("a rules engine with integer parameters \"Age\" set to 15 and \"Score\" set to 90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("I add a rule \"Age >= 18 and Score > 80\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.ThenAsync("the executed rule count should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Parse and render a rule expression")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Parse and render a rule expression")]
        public async global::System.Threading.Tasks.Task ParseAndRenderARuleExpression()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parse and render a rule expression", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
    await testRunner.GivenAsync("a rules engine with an integer parameter \"X\" set to 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.WhenAsync("I parse the rule \"X > 5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("the rendered expression should contain \"X\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.AndAsync("the rendered expression should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.AndAsync("the rendered expression should contain \"5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple rules with only some passing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rules Engine")]
        [global::Xunit.TraitAttribute("Description", "Multiple rules with only some passing")]
        public async global::System.Threading.Tasks.Task MultipleRulesWithOnlySomePassing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple rules with only some passing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
    await testRunner.GivenAsync("a rules engine with an integer parameter \"Value\" set to 50", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
    await testRunner.WhenAsync("I add a rule \"Value > 100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.AndAsync("I add a rule \"Value = 50\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("I add a rule \"Value < 10\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.AndAsync("I execute the rules engine", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.ThenAsync("the executed rule count should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RulesEngineFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await RulesEngineFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
