// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NAIware.Rules.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RuleServiceAPIFeature : object, global::Xunit.IClassFixture<RuleServiceAPIFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Rule Service API", "\tAs a consumer of the NAIware Rule Service\r\n\tI want to submit serialized models t" +
                "o the HTTP evaluation endpoint\r\n\tSo that I can evaluate them against a rules lib" +
                "rary and receive results", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RuleServiceApi.feature"
#line hidden
        
        public RuleServiceAPIFeature(RuleServiceAPIFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/RuleServiceApi.feature", "Feature: Rule Service API\r\n\tAs a consumer of the NAIware Rule Service\r\n\tI want to" +
                    " submit serialized models to the HTTP evaluation endpoint\r\n\tSo that I can evalua" +
                    "te them against a rules library and receive results\r\n\r\nScenario: Health endpoint" +
                    " reports healthy\r\n\tWhen I request the service health endpoint\r\n\tThen the respons" +
                    "e status should be \"OK\"\r\n\r\nScenario: MISMO XML is translated and evaluated via t" +
                    "he configured translator\r\n\tGiven a request for the \"Mortgage.Model\" loan applica" +
                    "tion model\r\n\tAnd the request uses the MISMO translator\r\n\tAnd the request payload" +
                    " is the file \"sample-loan-application.xml\" as \"Xml\"\r\n\tAnd the request uses the r" +
                    "ules library file \"MortgageEligibilityRules.json\"\r\n\tAnd the request execution mo" +
                    "de is \"Lenient\"\r\n\tWhen I post the evaluation request\r\n\tThen the response status " +
                    "should be \"OK\"\r\n\tAnd the evaluated context name should be \"Loan\"\r\n\tAnd the evalu" +
                    "ation should have succeeded\r\n\tAnd the total evaluated rules should be 3\r\n\tAnd th" +
                    "e matches should contain code \"BORR-001\"\r\n\tAnd the matches should contain code \"" +
                    "AMT-001\"\r\n\tAnd the mismatches should contain expression \"High Balance Loan\"\r\n\r\nS" +
                    "cenario: Inline XML payload is evaluated\r\n\tGiven a request for the \"Mortgage.Mod" +
                    "el\" loan application model\r\n\tAnd the request uses the MISMO translator\r\n\tAnd the" +
                    " request payload is the inline content of file \"sample-loan-application.xml\" as " +
                    "\"Xml\"\r\n\tAnd the request uses the inline rules library from file \"MortgageEligibi" +
                    "lityRules.json\"\r\n\tWhen I post the evaluation request\r\n\tThen the response status " +
                    "should be \"OK\"\r\n\tAnd the total evaluated rules should be 3\r\n\tAnd the matches sho" +
                    "uld contain code \"BORR-001\"\r\n\r\nScenario: Bad request when the model assembly is " +
                    "missing\r\n\tGiven a request referencing a missing model assembly \"DoesNotExist.dll" +
                    "\"\r\n\tAnd the request payload is the inline content \"<MESSAGE />\" as \"Xml\"\r\n\tAnd t" +
                    "he request uses the rules library file \"MortgageEligibilityRules.json\"\r\n\tWhen I " +
                    "post the evaluation request\r\n\tThen the response status should be \"BadRequest\"\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/RuleServiceApi.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Rule Service API", "\tAs a consumer of the NAIware Rule Service\r\n\tI want to submit serialized models t" +
                        "o the HTTP evaluation endpoint\r\n\tSo that I can evaluate them against a rules lib" +
                        "rary and receive results", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Health endpoint reports healthy", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(2)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I request the service health endpoint", null, null, "785642c824712e53aae0d3e1654aefc2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(2)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status should be \"OK\"", null, null, "1fff61d73697d954ad0661c1598fd4c5")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "4522e3fa9dbeb3529b025fbe7d50b014")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "MISMO XML is translated and evaluated via the configured translator", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(2)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a request for the \"Mortgage.Model\" loan application model", null, null, "178ae244d522ac5eaf4a725c8e2085fb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request uses the MISMO translator", null, null, "07a126d7d3c04050bab967beafe0163d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request payload is the file \"sample-loan-application.xml\" as \"Xml\"", null, null, "ab1ba3dc8dda7957bd5d20bf652a569d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request uses the rules library file \"MortgageEligibilityRules.json\"", null, null, "e785339aeebeb95fa82731671e09b789"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request execution mode is \"Lenient\"", null, null, "7cdf44ebb49b135384309f93d4e07650"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(2)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I post the evaluation request", null, null, "5e3cff467a85185bbde02d2ba0389199"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(2)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status should be \"OK\"", null, null, "62d5c9264f076f57b0ec00dd8e6e1e10"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the evaluated context name should be \"Loan\"", null, null, "da73a67549702958aa91a1b3f2a3bd7e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the evaluation should have succeeded", null, null, "01df5b40f109165eac904d88bcec1a33"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the total evaluated rules should be 3", null, null, "5d3fab330233d65f97d728bcdd487010"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the matches should contain code \"BORR-001\"", null, null, "246f705fe14d175d9ab60e080497c016"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the matches should contain code \"AMT-001\"", null, null, "ba447a004a43e350aabdd551610eb313"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the mismatches should contain expression \"High Balance Loan\"", null, null, "cfb841de58862358a5678ffb1049b582")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6f3ccfbb1757d6518885fb7780501241")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Inline XML payload is evaluated", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(2)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a request for the \"Mortgage.Model\" loan application model", null, null, "c81d0490c739e4588fa13b8f2b51454c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request uses the MISMO translator", null, null, "fca5e93f31edca51be8a0588c940f5c2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request payload is the inline content of file \"sample-loan-application.xml\" a" +
                                                            "s \"Xml\"", null, null, "dd9c1decb63a6053bc7ff84bf17f517b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request uses the inline rules library from file \"MortgageEligibilityRules.jso" +
                                                            "n\"", null, null, "009d26a0f9f6e750b77dd698fff84a54"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(2)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I post the evaluation request", null, null, "230cbd2795165351b29ccda7ef013753"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(2)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status should be \"OK\"", null, null, "3076e4e951611f5093599f2174d859c5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the total evaluated rules should be 3", null, null, "9d8663fceb9fb65588aaafc00fd3d9aa"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the matches should contain code \"BORR-001\"", null, null, "34a4d49a702e6b5094173588ccd67d05")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "678a57cfa77eed5ca2b2a1497f933351")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Bad request when the model assembly is missing", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(2)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a request referencing a missing model assembly \"DoesNotExist.dll\"", null, null, "543bebb2ef004e58bbe90a3839e0f7b1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request payload is the inline content \"<MESSAGE />\" as \"Xml\"", null, null, "0347e3334d4ae45faef7ffea91961a83"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the request uses the rules library file \"MortgageEligibilityRules.json\"", null, null, "e8519c720387e65ab7ff1bd626430f50"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(2)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I post the evaluation request", null, null, "1af62a0201d69c52a82eb035710378e0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(2)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status should be \"BadRequest\"", null, null, "4e8cc219b0b4945bbe6090cb999fcd9d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "5d1b8c667d55b45e9e09de74583db198"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("e9b4b4d6247af5569c6f924a7f7920e5", "Features/RuleServiceApi.feature", "Health endpoint reports healthy", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "785642c824712e53aae0d3e1654aefc2"}), "8f23077352c31b50ae005c59ff204b00", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I request the service health endpoint"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1fff61d73697d954ad0661c1598fd4c5"}), "0664b073a145bd5aa7360603d2cc06c6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status should be \"OK\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "4522e3fa9dbeb3529b025fbe7d50b014"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("017a6584a4d4385bbb6fa6423c728ba7", "Features/RuleServiceApi.feature", "MISMO XML is translated and evaluated via the configured translator", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "178ae244d522ac5eaf4a725c8e2085fb"}), "59651bdd3343665a8a4910a7835c7e29", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a request for the \"Mortgage.Model\" loan application model"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "07a126d7d3c04050bab967beafe0163d"}), "6796890e768bd45da113d28045d9c504", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request uses the MISMO translator"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab1ba3dc8dda7957bd5d20bf652a569d"}), "6a778ef76bdb975fb0f1c043ab42fe7b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request payload is the file \"sample-loan-application.xml\" as \"Xml\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e785339aeebeb95fa82731671e09b789"}), "41bd8d4297232c5dadaf0fd327b0d462", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request uses the rules library file \"MortgageEligibilityRules.json\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7cdf44ebb49b135384309f93d4e07650"}), "58a039b79e76fc5da1d491f2c90733bf", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request execution mode is \"Lenient\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5e3cff467a85185bbde02d2ba0389199"}), "e7083a99e1a69156a8160431768deb6f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I post the evaluation request"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "62d5c9264f076f57b0ec00dd8e6e1e10"}), "0ff35e94e318a056bd50060b68f4cf14", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status should be \"OK\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "da73a67549702958aa91a1b3f2a3bd7e"}), "3bbe38a60b3bd558be6bddb378c980fb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the evaluated context name should be \"Loan\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "01df5b40f109165eac904d88bcec1a33"}), "a55ee8e8424a275398056ec01f23f39e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the evaluation should have succeeded"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5d3fab330233d65f97d728bcdd487010"}), "cb4ec73c4df3db518f878864a7e97cad", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the total evaluated rules should be 3"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "246f705fe14d175d9ab60e080497c016"}), "d9fd88469708b25bbe87c23cf8cfe47d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the matches should contain code \"BORR-001\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ba447a004a43e350aabdd551610eb313"}), "47c1373d6166c95c80d2109260c226ba", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the matches should contain code \"AMT-001\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfb841de58862358a5678ffb1049b582"}), "f1fc9982ecd3825f9a0d1b1d35c78d9e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the mismatches should contain expression \"High Balance Loan\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6f3ccfbb1757d6518885fb7780501241"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("cbeefcb8f3ea185b9aa2353ab89c71d6", "Features/RuleServiceApi.feature", "Inline XML payload is evaluated", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c81d0490c739e4588fa13b8f2b51454c"}), "c34fb13c3c05d4509f6ecaa8e75378e9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a request for the \"Mortgage.Model\" loan application model"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fca5e93f31edca51be8a0588c940f5c2"}), "08a094338004375587164827bda79487", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request uses the MISMO translator"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dd9c1decb63a6053bc7ff84bf17f517b"}), "2e2b5ae33e530851a6731c20c26f7acf", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request payload is the inline content of file \"sample-loan-application.xml\" a" +
                                                "s \"Xml\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "009d26a0f9f6e750b77dd698fff84a54"}), "9ad5a1820e43b054955daef74f6ff950", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request uses the inline rules library from file \"MortgageEligibilityRules.jso" +
                                                "n\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "230cbd2795165351b29ccda7ef013753"}), "6210902cda15a950b2ee2c51b4ae499b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I post the evaluation request"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3076e4e951611f5093599f2174d859c5"}), "a4d735dd32994f5c9e329f791a0399d0", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status should be \"OK\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9d8663fceb9fb65588aaafc00fd3d9aa"}), "e8fd502cf394515ea5a40fd0a6ff80bb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the total evaluated rules should be 3"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "34a4d49a702e6b5094173588ccd67d05"}), "1f8b49256267fb5e9ab75727e1d18716", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the matches should contain code \"BORR-001\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "678a57cfa77eed5ca2b2a1497f933351"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0e4adca946635e5d897cfe5f6ad72d8a", "Features/RuleServiceApi.feature", "Bad request when the model assembly is missing", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "543bebb2ef004e58bbe90a3839e0f7b1"}), "c1f61a9e56794b52855afe830aa7816b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a request referencing a missing model assembly \"DoesNotExist.dll\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0347e3334d4ae45faef7ffea91961a83"}), "ec6b0cba5e056c5c974360d079011e34", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request payload is the inline content \"<MESSAGE />\" as \"Xml\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e8519c720387e65ab7ff1bd626430f50"}), "293ca460c6e9335182c9c6e3303d13cd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the request uses the rules library file \"MortgageEligibilityRules.json\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1af62a0201d69c52a82eb035710378e0"}), "efb59cd1d71c0859ba665e536cc4d37e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I post the evaluation request"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4e8cc219b0b4945bbe6090cb999fcd9d"}), "8e762c9ba3ed4952aed4c9eccd7f85d6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status should be \"BadRequest\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "5d1b8c667d55b45e9e09de74583db198"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(RuleServiceAPIFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(RuleServiceAPIFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(RuleServiceAPIFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Health endpoint reports healthy")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rule Service API")]
        [global::Xunit.TraitAttribute("Description", "Health endpoint reports healthy")]
        public async global::System.Threading.Tasks.Task HealthEndpointReportsHealthy()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Health endpoint reports healthy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.WhenAsync("I request the service health endpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.ThenAsync("the response status should be \"OK\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="MISMO XML is translated and evaluated via the configured translator")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rule Service API")]
        [global::Xunit.TraitAttribute("Description", "MISMO XML is translated and evaluated via the configured translator")]
        public async global::System.Threading.Tasks.Task MISMOXMLIsTranslatedAndEvaluatedViaTheConfiguredTranslator()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MISMO XML is translated and evaluated via the configured translator", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
 await testRunner.GivenAsync("a request for the \"Mortgage.Model\" loan application model", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
 await testRunner.AndAsync("the request uses the MISMO translator", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync("the request payload is the file \"sample-loan-application.xml\" as \"Xml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("the request uses the rules library file \"MortgageEligibilityRules.json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("the request execution mode is \"Lenient\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.WhenAsync("I post the evaluation request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
 await testRunner.ThenAsync("the response status should be \"OK\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
 await testRunner.AndAsync("the evaluated context name should be \"Loan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("the evaluation should have succeeded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("the total evaluated rules should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("the matches should contain code \"BORR-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("the matches should contain code \"AMT-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("the mismatches should contain expression \"High Balance Loan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Inline XML payload is evaluated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rule Service API")]
        [global::Xunit.TraitAttribute("Description", "Inline XML payload is evaluated")]
        public async global::System.Threading.Tasks.Task InlineXMLPayloadIsEvaluated()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Inline XML payload is evaluated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
 await testRunner.GivenAsync("a request for the \"Mortgage.Model\" loan application model", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
 await testRunner.AndAsync("the request uses the MISMO translator", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("the request payload is the inline content of file \"sample-loan-application.xml\" a" +
                        "s \"Xml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("the request uses the inline rules library from file \"MortgageEligibilityRules.jso" +
                        "n\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.WhenAsync("I post the evaluation request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
 await testRunner.ThenAsync("the response status should be \"OK\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
 await testRunner.AndAsync("the total evaluated rules should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("the matches should contain code \"BORR-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Bad request when the model assembly is missing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Rule Service API")]
        [global::Xunit.TraitAttribute("Description", "Bad request when the model assembly is missing")]
        public async global::System.Threading.Tasks.Task BadRequestWhenTheModelAssemblyIsMissing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bad request when the model assembly is missing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
 await testRunner.GivenAsync("a request referencing a missing model assembly \"DoesNotExist.dll\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
 await testRunner.AndAsync("the request payload is the inline content \"<MESSAGE />\" as \"Xml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("the request uses the rules library file \"MortgageEligibilityRules.json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.WhenAsync("I post the evaluation request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
 await testRunner.ThenAsync("the response status should be \"BadRequest\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RuleServiceAPIFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await RuleServiceAPIFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
